version: '3'
services:
  arborx_ci:
    image: dalg24/arborx_base:cuda-9.2
    volumes:
      # Cannot mount subdirectory jenkins_data/workspace/$JOBNAME in data
      # volume so have to mount the entire volume and climb up two directories.
      # NOTE: it is possible to find out what the actual mount point of the
      # volume that stores Jenkins home directory on the host but it is
      # probably wiser not to do so.
      - jenkins_data:$WORKSPACE/../..
    environment:
      - NPROCS=8
      - ARBORX_DIR=$WORKSPACE
      - CCACHE_DIR=$WORKSPACE/.ccache
      - CCACHE_MAXSIZE=10G
    command: bash -xe $WORKSPACE/docker/jenkins/build.sh
    cap_add:
      # required to mount DTK into Trilinos source directory
      - SYS_ADMIN
      # required to use CLang's LeakSanitizer
      - SYS_PTRACE
    network_mode: none
volumes:
  jenkins_data:
    external:
      name: $JENKINS_DATA_VOLUME
